version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "9000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php_server
    volumes:
      - ./public:/var/www/html

  laravel_app:
    image: talk-to-leads-laravel
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - php
